---
- name: Upgrade Packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoclean: true
    autoremove: true
    clean: true

- name: Upgrade Monitoring Packages
  ansible.builtin.import_tasks: upgrade_monitoring.yml
  when: vpn_role == "main
